apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
    name: iaweb-monitorering
    namespace: default
    labels:
        team: teamtag
spec:
    image: navikt/iaweb-monitorering:99c66898eba1c19e4047d24945730cc37ac43b56
    team: teamtag
    port: 8080
    ingresses:
        - https://iaweb-monitorering.nais.preprod.local/iaweb-monitorering
    liveness:
        path: /iaweb-monitorering/internal/isAlive
        initialDelay: 5
    readiness:
        path: /iaweb-monitorering/internal/isReady
        initialDelay: 5
    prometheus:
        enabled: true
        path: /iaweb-monitorering/internal/metrics