defaults: &defaults
  docker:
    - image: circleci/node

version: 2.1
jobs:
  bygg:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Bygg Docker image
          command: docker build -t "navikt/iaweb-monitorering:$CIRCLE_SHA1" .
      - run:
          name: Push Docker image
          command: |
            echo $DOCKER_PASSWORD | docker login --username $DOCKER_LOGIN --password-stdin
            docker push "navikt/iaweb-monitorering:$CIRCLE_SHA1"
            echo "Docker image: $CIRCLE_SHA1"

  deploy-til-dev-sbs:
    docker:
      - image: 'navikt/deployment-cli:v0.3.0'
    steps:
      - deploy:
          cluster: "dev-sbs"
          nais-yaml: "dev-sbs-nais.yaml"

  deploy-til-prod-sbs:
    docker:
      - image: 'navikt/deployment-cli:v0.3.0'
    steps:
      - deploy:
          cluster: "prod-sbs"
          nais-yaml: "prod-sbs-nais.yaml"

  deploy-til-dev-fss:
    docker:
      - image: 'navikt/deployment-cli:v0.3.0'
    steps:
      - deploy:
          cluster: "dev-fss"
          nais-yaml: "dev-fss-nais.yaml"

  deploy-til-prod-fss:
    docker:
      - image: 'navikt/deployment-cli:v0.3.0'
    steps:
      - deploy:
          cluster: "prod-fss"
          nais-yaml: "prod-fss-nais.yaml"          

commands:
  deploy:
    description: Deploy til et gitt miljø
    parameters:
      cluster:
        type: string
      nais-yaml:
        type: string
    steps:
      - checkout
      - run:
          name: Deploy til << parameters.cluster >>
          command: deployment-cli deploy create --cluster=<< parameters.cluster >> --repository=navikt/iaweb-monitorering --team=teamtag --resource=<< parameters.nais-yaml >> --version=$CIRCLE_SHA1 --ref=$CIRCLE_BRANCH

workflows:
  version: 2.1
  bygg_og_deploy:
    jobs:
      - bygg:
          context: NAIS deployment
      - deploy-til-dev-sbs:
          requires:
            - bygg
          filters:
            branches:
              only:
                - master
      - godkjenn-til-prod-sbs:
          type: approval
          requires:
            - bygg
          filters:
            branches:
              only:
                - master
      - deploy-til-prod-sbs:
          requires:
            - godkjenn-til-prod-sbs
          filters:
            branches:
              only:
                - master
      - deploy-til-dev-fss:
          requires:
            - bygg
          filters:
            branches:
              only:
                - master
      - godkjenn-til-prod-fss:
          type: approval
          requires:
            - bygg
          filters:
            branches:
              only:
                - master
      - deploy-til-prod-fss:
          requires:
            - godkjenn-til-prod-fss
          filters:
            branches:
              only:
                - master
