apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: iaweb-alerts
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  receivers:
    slack:
      channel: 'arbeidsgiver-teamia-utvikling'
      prependText: '<!here> | '
  alerts:
    - alert: applikasjon nede
      expr: min_over_time(iawebnav_p{app="iaweb-monitorering"}[2m]) < 0.5
      for: 2m
      description: "iawebnav er nede i prod"
      action: "sjekk https://iaweb-monitorering.nais.oera.no/iaweb-monitorering/internal/selftester for mer info"
